[package]
name = "horust"
version = "0.1.0"
authors = ["Federico Ponzi <federico.ponzi92@gmail.com>"]
edition = "2018"

[dependencies]
libc = "~0.2"
toml = "~0.5"
serde = {version = "~1.0", features = ["derive"] }
nix = "~0.16"
parse_duration = "~2.0"
clap = "~2.33"
structopt = "~0.3"