[package]
name = "horust"
version = "0.0.1"
authors = ["Federico Ponzi <federico.ponzi92@gmail.com>"]
description = "A complete supervisor and init system, designed for running in containers."
edition = "2018"
repository = "https://github.com/FedericoPonzi/horust"
readme = "README.md"
keywords = ["init", "container", "supervisor"]
categories = ["command-line-utilities"]

[dependencies]
log = "~0.4"
env_logger = "~0.7"
libc = "~0.2"
toml = "~0.5"
serde = {version = "~1.0", features = ["derive"] }
nix = "~0.16"
humantime-serde = "~0.1"
clap = "~2.33"
structopt = "~0.3"

[dev-dependencies]
tempdir = "~0.3"