[package]
name = "horust"
version = "0.1.3"
authors = ["Federico Ponzi <federico.ponzi92@gmail.com>"]
description = "A complete supervisor and init system, designed for running in containers."
edition = "2018"
license = "MIT"
repository = "https://github.com/FedericoPonzi/horust"
homepage = "https://github.com/FedericoPonzi/horust"
readme = "README.md"
keywords = ["init", "container", "supervisor"]
categories = ["command-line-utilities"]
include = [ "src/**/*", "Cargo.*", "LICENSE.txt", "README.md", ]

[dependencies]
structopt = "~0.3"
# Still not released: clap = { git = "https://github.com/clap-rs/clap/", rev = "28c46b5", version = "3.0.0-beta.1" }
crossbeam = "~0.7"
env_logger = "~0.7"
humantime-serde = "~0.1"
libc = "~0.2"
log = "~0.4"
nix = "~0.16"
reqwest = { version = "0.10", features = ["blocking", "json"], optional = true, default-features = false }
serde = {version = "~1.0", features = ["derive"] }
shlex = "~0.1"
toml = "~0.5"
maplit = "~1.0"
shellexpand = "~2.1"
anyhow = "1.0.40"
thiserror = "1.0.24"
itertools = "0.10.0"

[features]
default = ["http-healthcheck"]
http-healthcheck = ["reqwest"]

[dev-dependencies]
assert_cmd = "~0.11"
predicates = "~1.0"
tempdir = "~0.3"
rand = "~0.7"
