[build]
pre-build = [
    "apt-get update && apt-get install -y unzip && curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v28.3/protoc-28.3-linux-x86_64.zip && unzip protoc-28.3-linux-x86_64.zip -d /usr/local && rm protoc-28.3-linux-x86_64.zip"
]
