## This Dockerfile is used for building Horust in a conatiner while developing locally.
## It is meant to be run with the Horust project directory bind-mounted uder /usr/src/Horust

FROM rust:1.42
WORKDIR /usr/src/Horust
CMD ["/bin/bash"]

