# no name specified - filename will be used instead.
command = "/bigger/failing.sh second"
working-directory = "/tmp/"
start-after = ["database"]
start-delay = "2s"
[restart]
strategy = "always"
#restart-backoff = "10s"