name = "my-first-service"
command = "/home/isaacisback/dev/rust/horust/examples/services/healthcheck/first.sh first!"
working-directory = "/tmp/"
restart = "never"
start-delay = "2s"
#restart-backoff = "10s"
file_path = "/tmp/horust-ready"

[healthness]
