name = "second-service"
command = "/home/isaacisback/dev/rust/horust/examples/services/2/bigger/failing.sh second"
working-directory = "/tmp/"
restart = "on-failure"
start-after = ["my-first-service"]
start-delay = "2s"
#restart-backoff = "10s"